# Generated by Django 4.2.3 on 2023-07-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_comentario_comentarios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentarios',
            new_name='comentario',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nome_comentario',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
    ]
